services:
  moodle-nginx:
    image: nginx:latest
    container_name: moodle-nginx
    ports:
      - "9000:80"
    volumes:
      - moodle-code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moodle-php

  moodle-php:
    container_name: moodle-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - moodle-code:/var/www/html
      - moodledata:/var/www/moodledata
    depends_on:
      - moodle-db
    restart: always

  moodle-db:
    image: postgres:15
    container_name: moodle-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=w9zR5@y#sE!vP_r8k
      - POSTGRES_DB=moodle
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
  moodle-code:
  moodledata:
